# Generated by Django 2.2.7 on 2019-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invoice_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=1),
        ),
    ]
